#!/usr/bin/env python3
"""
Generate Ansible Inventory from Terraform Outputs
"""

import json
import os
import sys
from pathlib import Path

# Configuration
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
TERRAFORM_OUTPUT_FILE = PROJECT_ROOT / "ansible" / "inventory" / "terraform-output.json"
INVENTORY_FILE = PROJECT_ROOT / "ansible" / "inventory" / "hosts.ini"


def load_terraform_output():
    """Load Terraform output JSON"""
    if not TERRAFORM_OUTPUT_FILE.exists():
        print(f"ERROR: Terraform output file not found: {TERRAFORM_OUTPUT_FILE}")
        print("\nGenerate it with:")
        print("  cd terraform/environments/dev")
        print("  terraform output -json ansible_inventory_data > ../../../ansible/inventory/terraform-output.json")
        sys.exit(1)

    with open(TERRAFORM_OUTPUT_FILE) as f:
        return json.load(f)


def generate_inventory(tf_output):
    """Generate Ansible inventory from Terraform output"""

    master = tf_output["master"]
    workers = tf_output["workers"]

    # Separate workers by workload type
    stateless_workers = {k: v for k, v in workers.items() if v["workload"] == "stateless"}
    stateful_workers = {k: v for k, v in workers.items() if v["workload"] == "stateful"}

    inventory = []
    inventory.append("# =============================================================================")
    inventory.append("# Ansible Inventory - Generated from Terraform")
    inventory.append("# =============================================================================")
    inventory.append("# DO NOT EDIT MANUALLY - Generated by scripts/generate-inventory.py")
    inventory.append("# =============================================================================")
    inventory.append("")

    # Master nodes
    inventory.append("# -----------------------------------------------------------------------------")
    inventory.append("# K3s Master Nodes")
    inventory.append("# -----------------------------------------------------------------------------")
    inventory.append("[k3s_master]")
    inventory.append(f"{master['name']} ansible_host={master['external_ip']} ansible_user=ubuntu")
    inventory.append("")

    # Stateless workers
    inventory.append("# -----------------------------------------------------------------------------")
    inventory.append("# K3s Worker Nodes - Stateless")
    inventory.append("# -----------------------------------------------------------------------------")
    inventory.append("[k3s_workers_stateless]")
    for key, worker in stateless_workers.items():
        inventory.append(f"{worker['name']} ansible_host={worker['external_ip']} ansible_user=ubuntu")
    inventory.append("")

    # Stateful workers
    inventory.append("# -----------------------------------------------------------------------------")
    inventory.append("# K3s Worker Nodes - Stateful")
    inventory.append("# -----------------------------------------------------------------------------")
    inventory.append("[k3s_workers_stateful]")
    for key, worker in stateful_workers.items():
        inventory.append(f"{worker['name']} ansible_host={worker['external_ip']} ansible_user=ubuntu")
    inventory.append("")

    # Group aggregations
    inventory.append("# -----------------------------------------------------------------------------")
    inventory.append("# Group Aggregations")
    inventory.append("# -----------------------------------------------------------------------------")
    inventory.append("[k3s_workers:children]")
    inventory.append("k3s_workers_stateless")
    inventory.append("k3s_workers_stateful")
    inventory.append("")
    inventory.append("[k3s_cluster:children]")
    inventory.append("k3s_master")
    inventory.append("k3s_workers")
    inventory.append("")

    # Group variables
    inventory.append("# -----------------------------------------------------------------------------")
    inventory.append("# Group Variables")
    inventory.append("# -----------------------------------------------------------------------------")
    inventory.append("[k3s_master:vars]")
    inventory.append("k3s_role=master")
    inventory.append("")
    inventory.append("[k3s_workers_stateless:vars]")
    inventory.append("k3s_role=worker")
    inventory.append("workload_type=stateless")
    inventory.append("")
    inventory.append("[k3s_workers_stateful:vars]")
    inventory.append("k3s_role=worker")
    inventory.append("workload_type=stateful")
    inventory.append("")
    inventory.append("[k3s_cluster:vars]")
    inventory.append("ansible_python_interpreter=/usr/bin/python3")
    inventory.append("ansible_ssh_private_key_file=~/.ssh/orange-wallet-key")
    inventory.append("")

    return "\n".join(inventory)


def main():
    """Main function"""
    print("Generating Ansible inventory from Terraform outputs...")

    # Load Terraform output
    tf_output = load_terraform_output()

    # Generate inventory
    inventory_content = generate_inventory(tf_output)

    # Write inventory file
    with open(INVENTORY_FILE, "w") as f:
        f.write(inventory_content)

    print(f"✅ Inventory generated: {INVENTORY_FILE}")
    print("\nGenerated hosts:")
    print(f"  Master: {tf_output['master']['name']} ({tf_output['master']['external_ip']})")
    for key, worker in tf_output['workers'].items():
        print(f"  Worker: {worker['name']} ({worker['external_ip']}) - {worker['workload']}")

    print("\nVerify connectivity:")
    print("  cd ../ansible")
    print("  ansible all -m ping")


if __name__ == "__main__":
    main()
